# coding: utf-8

"""
    MINDBODY Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.contact_log_sub_type import ContactLogSubType  # noqa: E501
from swagger_client.rest import ApiException


class TestContactLogSubType(unittest.TestCase):
    """ContactLogSubType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContactLogSubType(self):
        """Test ContactLogSubType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.contact_log_sub_type.ContactLogSubType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
