# coding: utf-8

"""
    MINDBODY Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.staff_permission_group import StaffPermissionGroup  # noqa: E501
from swagger_client.rest import ApiException


class TestStaffPermissionGroup(unittest.TestCase):
    """StaffPermissionGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStaffPermissionGroup(self):
        """Test StaffPermissionGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.staff_permission_group.StaffPermissionGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
