# coding: utf-8

"""
    MINDBODY Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user_token_api import UserTokenApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserTokenApi(unittest.TestCase):
    """UserTokenApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.user_token_api.UserTokenApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_user_token_issue(self):
        """Test case for user_token_issue

        Get a staff user token.  # noqa: E501
        """
        pass

    def test_user_token_revoke(self):
        """Test case for user_token_revoke

        Revoke a user token.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
