# coding: utf-8

"""
    MINDBODY Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sale_api import SaleApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSaleApi(unittest.TestCase):
    """SaleApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.sale_api.SaleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sale_checkout_shopping_cart(self):
        """Test case for sale_checkout_shopping_cart

        Purchase pricing options, packages, retail products, or tips for a client.  # noqa: E501
        """
        pass

    def test_sale_get_accepted_card_types(self):
        """Test case for sale_get_accepted_card_types

        Get credit cards types that a site accepts.  # noqa: E501
        """
        pass

    def test_sale_get_contracts(self):
        """Test case for sale_get_contracts

        Get contracts available for purchase at a site.  # noqa: E501
        """
        pass

    def test_sale_get_custom_payment_methods(self):
        """Test case for sale_get_custom_payment_methods

        Get payment methods that can be used to pay for sales at a site.  # noqa: E501
        """
        pass

    def test_sale_get_gift_cards(self):
        """Test case for sale_get_gift_cards

        Get gift cards available for purchase at a site.  # noqa: E501
        """
        pass

    def test_sale_get_packages(self):
        """Test case for sale_get_packages

        Get packages available for purchase at a site.  # noqa: E501
        """
        pass

    def test_sale_get_products(self):
        """Test case for sale_get_products

        Get retail products available for purchase at a site.  # noqa: E501
        """
        pass

    def test_sale_get_sales(self):
        """Test case for sale_get_sales

        Get sales completed at a site.  # noqa: E501
        """
        pass

    def test_sale_get_services(self):
        """Test case for sale_get_services

        Get pricing options available for purchase at a site  # noqa: E501
        """
        pass

    def test_sale_purchase_contract(self):
        """Test case for sale_purchase_contract

        Purchase a contract for a client.  # noqa: E501
        """
        pass

    def test_sale_purchase_gift_card(self):
        """Test case for sale_purchase_gift_card

        Purchase a gift card for a client.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
