# coding: utf-8

"""
    MINDBODY Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.remove_client_from_class_response import RemoveClientFromClassResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestRemoveClientFromClassResponse(unittest.TestCase):
    """RemoveClientFromClassResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRemoveClientFromClassResponse(self):
        """Test RemoveClientFromClassResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.remove_client_from_class_response.RemoveClientFromClassResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
