# coding: utf-8

"""
    MINDBODY Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.add_appointment_request import AddAppointmentRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestAddAppointmentRequest(unittest.TestCase):
    """AddAppointmentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddAppointmentRequest(self):
        """Test AddAppointmentRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.add_appointment_request.AddAppointmentRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
