# coding: utf-8

"""
    MINDBODY Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.class_api import ClassApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClassApi(unittest.TestCase):
    """ClassApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.class_api.ClassApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_class_add_client_to_class(self):
        """Test case for class_add_client_to_class

        Book a client into a class.  # noqa: E501
        """
        pass

    def test_class_get_class_descriptions(self):
        """Test case for class_get_class_descriptions

        Get class descriptions.  # noqa: E501
        """
        pass

    def test_class_get_class_schedules(self):
        """Test case for class_get_class_schedules

        Get class schedules.  # noqa: E501
        """
        pass

    def test_class_get_class_visits(self):
        """Test case for class_get_class_visits

        Get information about clients booked in a class.  # noqa: E501
        """
        pass

    def test_class_get_classes(self):
        """Test case for class_get_classes

        Get scheduled classes.  # noqa: E501
        """
        pass

    def test_class_get_waitlist_entries(self):
        """Test case for class_get_waitlist_entries

        Get waiting list entries.  # noqa: E501
        """
        pass

    def test_class_remove_client_from_class(self):
        """Test case for class_remove_client_from_class

        Remove a client from a class.  # noqa: E501
        """
        pass

    def test_class_remove_from_waitlist(self):
        """Test case for class_remove_from_waitlist

        Remove a client from a waiting list.  # noqa: E501
        """
        pass

    def test_class_substitute_class_teacher(self):
        """Test case for class_substitute_class_teacher

        Substitute a class teacher.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
