# coding: utf-8

"""
    MINDBODY Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.checkout_item import CheckoutItem  # noqa: E501
from swagger_client.rest import ApiException


class TestCheckoutItem(unittest.TestCase):
    """CheckoutItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCheckoutItem(self):
        """Test CheckoutItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.checkout_item.CheckoutItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
