# coding: utf-8

"""
    MINDBODY Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.get_locations_response import GetLocationsResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestGetLocationsResponse(unittest.TestCase):
    """GetLocationsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetLocationsResponse(self):
        """Test GetLocationsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.get_locations_response.GetLocationsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
