# coding: utf-8

"""
    MINDBODY Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.membership_type_restriction import MembershipTypeRestriction  # noqa: E501
from swagger_client.rest import ApiException


class TestMembershipTypeRestriction(unittest.TestCase):
    """MembershipTypeRestriction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMembershipTypeRestriction(self):
        """Test MembershipTypeRestriction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.membership_type_restriction.MembershipTypeRestriction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
