# coding: utf-8

"""
    MINDBODY Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.appointment_api import AppointmentApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAppointmentApi(unittest.TestCase):
    """AppointmentApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.appointment_api.AppointmentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_appointment_add_apppointment(self):
        """Test case for appointment_add_apppointment

        Book a new appointment.  # noqa: E501
        """
        pass

    def test_appointment_get_active_session_times(self):
        """Test case for appointment_get_active_session_times

        Get active session times.  # noqa: E501
        """
        pass

    def test_appointment_get_appointment_options(self):
        """Test case for appointment_get_appointment_options

        Get appointment-related settings.  # noqa: E501
        """
        pass

    def test_appointment_get_bookable_items(self):
        """Test case for appointment_get_bookable_items

        Get staff appointment availability.  # noqa: E501
        """
        pass

    def test_appointment_get_schedule_items(self):
        """Test case for appointment_get_schedule_items

        Get appointment schedule.  # noqa: E501
        """
        pass

    def test_appointment_get_staff_appointments(self):
        """Test case for appointment_get_staff_appointments

        Get appointments grouped by staff member.  # noqa: E501
        """
        pass

    def test_appointment_update_apppointment(self):
        """Test case for appointment_update_apppointment

        Update an existing appointment.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
