# coding: utf-8

"""
    MINDBODY Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.client_api import ClientApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClientApi(unittest.TestCase):
    """ClientApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.client_api.ClientApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_client_add_arrival(self):
        """Test case for client_add_arrival

        Add an arrival for a client.  # noqa: E501
        """
        pass

    def test_client_add_client(self):
        """Test case for client_add_client

        Add a client to a site.  # noqa: E501
        """
        pass

    def test_client_add_contact_log(self):
        """Test case for client_add_contact_log

        Add a contact log to a client's account.  # noqa: E501
        """
        pass

    def test_client_get_active_client_memberships(self):
        """Test case for client_get_active_client_memberships

        Get a client's active memberships.  # noqa: E501
        """
        pass

    def test_client_get_client_account_balances(self):
        """Test case for client_get_client_account_balances

        Get account balance information for one or more client(s).  # noqa: E501
        """
        pass

    def test_client_get_client_contracts(self):
        """Test case for client_get_client_contracts

        Get contracts that a client has purchased.  # noqa: E501
        """
        pass

    def test_client_get_client_formula_notes(self):
        """Test case for client_get_client_formula_notes

        Get a client's formula notes.  # noqa: E501
        """
        pass

    def test_client_get_client_indexes(self):
        """Test case for client_get_client_indexes

        Get a site's configured client indexes and client index values.  # noqa: E501
        """
        pass

    def test_client_get_client_purchases(self):
        """Test case for client_get_client_purchases

        Get a client's purchase history.  # noqa: E501
        """
        pass

    def test_client_get_client_referral_types(self):
        """Test case for client_get_client_referral_types

        Get a site's configured client referral types.  # noqa: E501
        """
        pass

    def test_client_get_client_services(self):
        """Test case for client_get_client_services

        Get pricing options that a client has purchased.  # noqa: E501
        """
        pass

    def test_client_get_client_visits(self):
        """Test case for client_get_client_visits

        Get a client's visit history.  # noqa: E501
        """
        pass

    def test_client_get_clients(self):
        """Test case for client_get_clients

        Get clients.  # noqa: E501
        """
        pass

    def test_client_get_contact_logs(self):
        """Test case for client_get_contact_logs

        Get contact logs on a client's account.  # noqa: E501
        """
        pass

    def test_client_get_cross_regional_client_associations(self):
        """Test case for client_get_cross_regional_client_associations

        Get a client's cross regional site associations.  # noqa: E501
        """
        pass

    def test_client_get_custom_client_fields(self):
        """Test case for client_get_custom_client_fields

        Get a site's configured custom client fields.  # noqa: E501
        """
        pass

    def test_client_get_required_client_fields(self):
        """Test case for client_get_required_client_fields

        Get client required fields for a site.  # noqa: E501
        """
        pass

    def test_client_send_password_reset_email(self):
        """Test case for client_send_password_reset_email

        Send a password reset email to a client.  # noqa: E501
        """
        pass

    def test_client_update_client(self):
        """Test case for client_update_client

        Update a client at a site.  # noqa: E501
        """
        pass

    def test_client_update_client_service(self):
        """Test case for client_update_client_service

        Update a client's purchase pricing option.  # noqa: E501
        """
        pass

    def test_client_update_client_visit(self):
        """Test case for client_update_client_visit

        Update a client's visit.  # noqa: E501
        """
        pass

    def test_client_update_contact_log(self):
        """Test case for client_update_contact_log

        Update a contact log on a client's account.  # noqa: E501
        """
        pass

    def test_client_upload_client_document(self):
        """Test case for client_upload_client_document

        Upload a document to a client's profile.  # noqa: E501
        """
        pass

    def test_client_upload_client_photo(self):
        """Test case for client_upload_client_photo

        Upload a profile photo to a client's profile.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
