=begin
#MINDBODY Public API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v6

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.6

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::GetWaitlistEntriesResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GetWaitlistEntriesResponse' do
  before do
    # run before each test
    @instance = SwaggerClient::GetWaitlistEntriesResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GetWaitlistEntriesResponse' do
    it 'should create an instance of GetWaitlistEntriesResponse' do
      expect(@instance).to be_instance_of(SwaggerClient::GetWaitlistEntriesResponse)
    end
  end
  describe 'test attribute "pagination_response"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "waitlist_entries"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
