=begin
#MINDBODY Public API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v6

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.6

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::ClientApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ClientApi' do
  before do
    # run before each test
    @instance = SwaggerClient::ClientApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ClientApi' do
    it 'should create an instance of ClientApi' do
      expect(@instance).to be_instance_of(SwaggerClient::ClientApi)
    end
  end

  # unit tests for client_add_arrival
  # Add an arrival for a client.
  # @param request 
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @return [AddArrivalResponse]
  describe 'client_add_arrival test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for client_add_client
  # Add a client to a site.
  # The &#x60;FirstName&#x60; and &#x60;LastName&#x60; parameters are always required in this request. All other parameters are optional, but note that any of the optional parameters could be required by a particular business, depending on how the business has configured the site settings.    Use after calling the &#x60;GetRequiredClientFields&#x60; endpoint to make sure you are collecting all required pieces of information.
  # @param request 
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @return [AddClientResponse]
  describe 'client_add_client test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for client_add_contact_log
  # Add a contact log to a client&#39;s account.
  # @param request 
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @return [ContactLog]
  describe 'client_add_contact_log test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for client_get_active_client_memberships
  # Get a client&#39;s active memberships.
  # @param request_client_id The ID of the client whose membership was requested.
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @option opts [Integer] :request_limit Number of results to include, defaults to 100
  # @option opts [Integer] :request_location_id The ID of the location where the requested membership was created.
  # @option opts [Integer] :request_offset Page offset, defaults to 0.
  # @return [GetActiveClientMembershipsResponse]
  describe 'client_get_active_client_memberships test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for client_get_client_account_balances
  # Get account balance information for one or more client(s).
  # @param request_client_ids The list of clients IDs for which you want account balances.
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @option opts [DateTime] :request_balance_date The date you want a balance relative to.   Default: **the current date**
  # @option opts [Integer] :request_class_id The class ID of the event for which you want a balance.
  # @option opts [Integer] :request_limit Number of results to include, defaults to 100
  # @option opts [Integer] :request_offset Page offset, defaults to 0.
  # @return [GetClientAccountBalancesResponse]
  describe 'client_get_client_account_balances test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for client_get_client_contracts
  # Get contracts that a client has purchased.
  # @param request_client_id The ID of the client.
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @option opts [Integer] :request_client_associated_sites_offset Determines how many sites are skipped over when retrieving a client’s cross regional contracts. Used when a client ID is linked to more than ten sites in an organization. Only a maximum of ten site databases are queried when this call is made and &#x60;CrossRegionalLookup&#x60; is set to &#x60;true&#x60;. To change which sites are queried, change this offset value.  Default: **0**
  # @option opts [BOOLEAN] :request_cross_regional_lookup When &#x60;true&#x60;, indicates that the requesting client’s cross regional contracts are returned, if any.&lt;br /&gt;  When &#x60;false&#x60;, indicates that cross regional contracts are not returned.
  # @option opts [Integer] :request_limit Number of results to include, defaults to 100
  # @option opts [Integer] :request_offset Page offset, defaults to 0.
  # @return [GetClientContractsResponse]
  describe 'client_get_client_contracts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for client_get_client_formula_notes
  # Get a client&#39;s formula notes.
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @option opts [Integer] :request_appointment_id The appointment ID of the appointment that the formula notes are related to.
  # @option opts [String] :request_client_id The client ID of the client whose formula notes are being requested.
  # @option opts [Integer] :request_limit Number of results to include, defaults to 100
  # @option opts [Integer] :request_offset Page offset, defaults to 0.
  # @return [GetClientFormulaNotesResponse]
  describe 'client_get_client_formula_notes test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for client_get_client_indexes
  # Get a site&#39;s configured client indexes and client index values.
  # Client indexes are used to analyze client demographics. A business owner can set up different categories with sets of values which they can assign to each client. Client indexes are used in client searches, for tagging clients so that the owner can send mass emails to similar groups, and for many reports.    For more information, see Client Indexes and [Client Index Values (video tutorial)](https://support.mindbodyonline.com/s/article/203261653-Client-indexes-and-client-index-values-video-tutorial?language&#x3D;en_USclient).
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @option opts [BOOLEAN] :request_required_only When &#x60;true&#x60;, filters the results to only indexes that are required on creation.&lt;br /&gt;  When &#x60;false&#x60; or omitted, returns all of the client indexes.
  # @return [GetClientIndexesResponse]
  describe 'client_get_client_indexes test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for client_get_client_purchases
  # Get a client&#39;s purchase history.
  # @param request_client_id The ID of the client you are querying for purchases.
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @option opts [DateTime] :request_end_date Filters results to purchases made before this timestamp.&lt;br /&gt;  Default: **end of today**
  # @option opts [Integer] :request_limit Number of results to include, defaults to 100
  # @option opts [Integer] :request_offset Page offset, defaults to 0.
  # @option opts [Integer] :request_sale_id Filters results to the single record associated with this ID.
  # @option opts [DateTime] :request_start_date Filters results to purchases made on or after this timestamp.&lt;br /&gt;  Default: **now**
  # @return [GetClientPurchasesResponse]
  describe 'client_get_client_purchases test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for client_get_client_referral_types
  # Get a site&#39;s configured client referral types.
  # Gets a list of referral types. Referral types are options that new clients can choose to identify how they learned about the business. Referral types are typically used for the sign-up process.
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @option opts [BOOLEAN] :request_include_inactive When &#x60;true&#x60;, filters the results to include subtypes and inactive referral types.&lt;br /&gt;  When &#x60;false&#x60;, includes no subtypes and only active types.
  # @return [GetClientReferralTypesResponse]
  describe 'client_get_client_referral_types test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for client_get_client_services
  # Get pricing options that a client has purchased.
  # @param request_client_id The ID of the client to query. The results are a list of pricing options that the client has purchased. Note that “service” and “pricing option” are synonymous in this section of the documentation.
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @option opts [Integer] :request_class_id Filters results to only those pricing options that can be used to pay for this class.
  # @option opts [Integer] :request_client_associated_sites_offset Used to retrieve a client’s pricing options from multiple sites within an organization when the client is associated with more than ten sites. To change which ten sites are searched, change this offset value. A value of 0 means that no sites are skipped and the first ten sites are returned. You can use the &#x60;CrossRegionalClientAssociations&#x60; value from &#x60;GET CrossRegionalClientAssociations&#x60; to determine how many sites the client is associated with. Note that you must always have &#x60;CrossRegionalLookup&#x60; set to &#x60;true&#x60; to use this parameter.&lt;br /&gt;  Default: **0**    For example, if a client is associated with 25 sites, you need to call &#x60;GetClientServices&#x60; three times, as follows:  * Use &#x60;GET CrossRegionalClientAssociations&#x60; to determine how many sites a client is associated with, which tells you how many additional calls you need to make.  * Either omit &#x60;ClientAssociatedSitesOffset&#x60; or set it to 0 to return the client’s services (pricing options) from sites 1-10.  * Set &#x60;ClientAssociatedSitesOffset&#x60; to 10 to return the client pricing options from sites 11-20  * Set &#x60;ClientAssociatedSitesOffset&#x60; to 20 to return the client pricing options from sites 21-25
  # @option opts [BOOLEAN] :request_cross_regional_lookup Used to retrieve a client’s pricing options from multiple sites within an organization. When included and set to &#x60;true&#x60;, it searches a maximum of ten sites with which this client is associated. When a client is associated with more than ten sites, use &#x60;ClientAssociatedSitesOffset&#x60; as many times as needed to search the additional sites with which the client is associated. You can use the &#x60;CrossRegionalClientAssociations&#x60; value from &#x60;GET CrossRegionalClientAssociations&#x60; to determine how many sites the client is associated with. Note that a &#x60;SiteID&#x60; is returned and populated in the &#x60;ClientServices&#x60; response when &#x60;CrossRegionalLookup&#x60; is set to &#x60;true&#x60;.  Default: **false**
  # @option opts [DateTime] :request_end_date Filters results to pricing options that are valid on or before this date.
  # @option opts [Integer] :request_limit Number of results to include, defaults to 100
  # @option opts [Array<Integer>] :request_location_ids Filters results to pricing options that can be used at the listed location IDs.
  # @option opts [Integer] :request_offset Page offset, defaults to 0.
  # @option opts [Array<Integer>] :request_program_ids Filters results to pricing options that belong to one of the given program IDs.
  # @option opts [Integer] :request_session_type_id Filters results to pricing options that will pay for the given session type ID. Use this to find pricing options that will pay for a specific appointment type.
  # @option opts [BOOLEAN] :request_show_active_only When &#x60;true&#x60;, includes active services only.  Default: **false**
  # @option opts [DateTime] :request_start_date Filters results to pricing options that are valid on or after this date.
  # @option opts [Integer] :request_visit_count A filter on the minimum number of visits a service can pay for.
  # @return [GetClientServicesResponse]
  describe 'client_get_client_services test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for client_get_client_visits
  # Get a client&#39;s visit history.
  # @param request_client_id The ID of the requested client.
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @option opts [Integer] :request_client_associated_sites_offset The number of sites to skip when returning the site associated with a client.
  # @option opts [BOOLEAN] :request_cross_regional_lookup When &#x60;true&#x60;, indicates that past and scheduled client visits across all sites in the region are returned.&lt;br /&gt;  When &#x60;false&#x60;, indicates that only visits at the current site are returned.
  # @option opts [DateTime] :request_end_date The date past which class visits are not returned.  Default: **today’s date**
  # @option opts [Integer] :request_limit Number of results to include, defaults to 100
  # @option opts [Integer] :request_offset Page offset, defaults to 0.
  # @option opts [DateTime] :request_start_date The date before which class visits are not returned.  Default: **the end date**
  # @option opts [BOOLEAN] :request_unpaids_only When &#x60;true&#x60;, indicates that only visits that have not been paid for are returned.&lt;br /&gt;  When &#x60;false&#x60;, indicates that all visits are returned, regardless of whether they have been paid for.&lt;br /&gt;  Default: **false**
  # @return [GetClientVisitsResponse]
  describe 'client_get_client_visits test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for client_get_clients
  # Get clients.
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @option opts [Array<String>] :request_client_i_ds The requested client IDs.  Default: **all IDs** that the authenticated user’s access level allows.
  # @option opts [BOOLEAN] :request_is_prospect When &#x60;true&#x60;, filters the results to include only those clients marked as prospects for the business.&lt;br /&gt;  When &#x60;false&#x60;, indicates that only those clients who are not marked prospects should be returned.
  # @option opts [DateTime] :request_last_modified_date Filters the results to include only the clients that have been modified on or after this date.
  # @option opts [Integer] :request_limit Number of results to include, defaults to 100
  # @option opts [Integer] :request_offset Page offset, defaults to 0.
  # @option opts [String] :request_search_text Text to use in the search. Can include FirstName, LastName, and Email. Note that user credentials must be provided.
  # @return [GetClientsResponse]
  describe 'client_get_clients test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for client_get_contact_logs
  # Get contact logs on a client&#39;s account.
  # This endpoint contains a variety of filters that can return not just all contact logs, but also system-generated contact logs, contact logs assigned to specific staff members, and contact logs of specific types or subtypes.
  # @param request_client_id The ID of the client whose contact logs are being requested.
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @option opts [DateTime] :request_end_date Filters the results to contact logs created before this date.&lt;br /&gt;  Default: **the start date**
  # @option opts [Integer] :request_limit Number of results to include, defaults to 100
  # @option opts [Integer] :request_offset Page offset, defaults to 0.
  # @option opts [BOOLEAN] :request_show_system_generated When &#x60;true&#x60;, system-generated contact logs are returned in the results.&lt;br /&gt;  Default: **false**
  # @option opts [Array<Integer>] :request_staff_ids Filters the results to return contact logs assigned to one or more staff IDs.
  # @option opts [DateTime] :request_start_date Filters the results to contact logs created on or after this date.&lt;br /&gt;  Default: **the current date**
  # @option opts [Array<Integer>] :request_subtype_ids Filters the results to contact logs assigned one or more of these subtype IDs.
  # @option opts [Array<Integer>] :request_type_ids Filters the results to contact logs assigned one or more of these type IDs.
  # @return [GetContactLogsResponse]
  describe 'client_get_contact_logs test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for client_get_cross_regional_client_associations
  # Get a client&#39;s cross regional site associations.
  # Returns a list of sites that a particular client ID (also referred to as an RSSID) or a client email address is associated with in a cross-regional organization. Either the &#x60;ClientID&#x60; or &#x60;Email&#x60; parameter is required. If both are provided, the &#x60;ClientID&#x60; is used.    Use this endpoint to retrieve information for other Public API endpoints, about the same client at multiple sites within an organization. To use this endpoint, your developer account must have been granted permission to the site’s entire organization.    Note that this endpoint does not work on the Developer Sandbox site, as it is not set up for cross-regional use cases.
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @option opts [String] :request_client_id Looks up the cross regional associations by the client’s ID. Either &#x60;ClientId&#x60; or &#x60;Email&#x60; must be provided. If both are provided, the &#x60;ClientId&#x60; is used by default.
  # @option opts [String] :request_email Looks up the cross regional associations by the client’s email address. Either &#x60;ClientId&#x60; or &#x60;Email&#x60; must be provided. If both are provided, the &#x60;ClientId&#x60; is used by default.
  # @option opts [Integer] :request_limit Number of results to include, defaults to 100
  # @option opts [Integer] :request_offset Page offset, defaults to 0.
  # @return [GetCrossRegionalClientAssociationsResponse]
  describe 'client_get_cross_regional_client_associations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for client_get_custom_client_fields
  # Get a site&#39;s configured custom client fields.
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @option opts [Integer] :request_limit Number of results to include, defaults to 100
  # @option opts [Integer] :request_offset Page offset, defaults to 0.
  # @return [GetCustomClientFieldsResponse]
  describe 'client_get_custom_client_fields test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for client_get_required_client_fields
  # Get client required fields for a site.
  # Gets the list of fields that a new client has to fill out in business mode, specifically for the sign-up process. &#x60;AddClient&#x60; and &#x60;UpdateClient&#x60; validate against these fields.    This endpoint has no query parameters.
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @return [GetRequiredClientFieldsResponse]
  describe 'client_get_required_client_fields test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for client_send_password_reset_email
  # Send a password reset email to a client.
  # @param request 
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @return [Object]
  describe 'client_send_password_reset_email test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for client_update_client
  # Update a client at a site.
  # Updates an existing client for a specific subscriber. Use this endpoint as follows:  * If you need to update the &#x60;ReferredBy&#x60; parameter, use this endpoint after calling &#x60;GET ClientReferralTypes&#x60;.  * When updating a client’s home location, use after calling &#x60;GET Locations&#x60;.  * If you are updating a client’s stored credit card, use after calling &#x60;GET AcceptedCardTypes&#x60; so that you can make sure the card is a type that is accepted at the subscriber.  If this endpoint is used on a cross-regional site, passing in a client’s RSSID and email address creates a cross-regional link. This means that the client is created in cross-regional sites where the client does not exist and &#x60;GET CrossRegionalClientAssociations&#x60; returns all appropriate cross-regional sites. When &#x60;CrossRegionalUpdate&#x60; is omitted or set to &#x60;true&#x60;, the client’s updated information is propagated to all of the region’s sites. If &#x60;CrossRegionalUpdate&#x60; is set to &#x60;false&#x60;, only the local client is updated.    Note that the following items cannot be updated for a cross-regional client:  * &#x60;ClientIndexes&#x60;  * &#x60;ClientRelationships&#x60;  * &#x60;CustomClientFields&#x60;  * &#x60;SalesReps&#x60;  * &#x60;SendAccountEmails&#x60;  * &#x60;SendAccountTexts&#x60;  * &#x60;SendPromotionalEmails&#x60;  * &#x60;SendPromotionalTexts&#x60;  * &#x60;SendScheduleEmails&#x60;  * &#x60;SendScheduleTexts&#x60;
  # @param request 
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @return [UpdateClientResponse]
  describe 'client_update_client test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for client_update_client_service
  # Update a client&#39;s purchase pricing option.
  # Updates the active date and/or expiration date of a client pricing option. This request requires staff user credentials. If the active date is modified, the expiration date is also modified accordingly. If the expiration date is modified, the active date is unchanged.
  # @param request 
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @return [UpdateClientServiceResponse]
  describe 'client_update_client_service test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for client_update_client_visit
  # Update a client&#39;s visit.
  # @param request 
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @return [UpdateClientVisitResponse]
  describe 'client_update_client_visit test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for client_update_contact_log
  # Update a contact log on a client&#39;s account.
  # @param request 
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @return [ContactLog]
  describe 'client_update_contact_log test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for client_upload_client_document
  # Upload a document to a client&#39;s profile.
  # Returns a string representation of the image byte array. The maximum document size is 1MB.    The maximum size file that can be uploaded is 4 MB.
  # @param request 
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @return [UploadClientDocumentResponse]
  describe 'client_upload_client_document test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for client_upload_client_photo
  # Upload a profile photo to a client&#39;s profile.
  # The maximum file size is 4 MB and acceptable file types are:  * bmp  * jpeg  * gif  * tiff  * png
  # @param request 
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @return [UploadClientPhotoResponse]
  describe 'client_upload_client_photo test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
