=begin
#MINDBODY Public API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v6

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.6

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::StaffApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StaffApi' do
  before do
    # run before each test
    @instance = SwaggerClient::StaffApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StaffApi' do
    it 'should create an instance of StaffApi' do
      expect(@instance).to be_instance_of(SwaggerClient::StaffApi)
    end
  end

  # unit tests for staff_get_staff
  # Get staff members at a site.
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @option opts [Array<String>] :request_filters Filters to apply to the search. Possible values are:  * StaffViewable  * AppointmentInstructor  * ClassInstructor  * Male  * Female
  # @option opts [Integer] :request_limit Number of results to include, defaults to 100
  # @option opts [Integer] :request_location_id Return only staff members that are available at the specified location. You must supply a valid &#x60;SessionTypeID&#x60; and &#x60;StartDateTime&#x60; to use this parameter.
  # @option opts [Integer] :request_offset Page offset, defaults to 0.
  # @option opts [Integer] :request_session_type_id Return only staff members that are available for the specified session type. You must supply a valid &#x60;StartDateTime&#x60; and &#x60;LocationID&#x60; to use this parameter.
  # @option opts [Array<Integer>] :request_staff_ids A list of the requested staff IDs.
  # @option opts [DateTime] :request_start_date_time Return only staff members that are available at the specified date and time. You must supply a valid &#x60;SessionTypeID&#x60; and &#x60;LocationID&#x60; to use this parameter.
  # @return [GetStaffResponse]
  describe 'staff_get_staff test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for staff_get_staff_permissions
  # Get configured staff permissions for a staff member.
  # @param request_staff_id The ID of the staff member whose permissions you want to return.
  # @param site_id ID of the site from which to pull data.
  # @param version 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization A staff user authorization token.
  # @return [GetStaffPermissionsResponse]
  describe 'staff_get_staff_permissions test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
